### PR TITLE
Automatically add semi-colon at the end of evaluation tags

### PR DESCRIPTION
**Pull request by byroot**
To be more consistent with underscore.js template function

Example:

``` ejs
<% var foo = "bar" %>
```

Will work fine with `_.template`, but produce a syntax error with `ruby-ejs``

### CODE REVIEW

**Comment by sstephenson** [comment]
Thank you. Could you add a test case for this too?

**Comment by byroot** [comment]
Off course, wait a minute.

**Comment by byroot** [comment]
I've squashed the test with the initial commit.

**Comment by sstephenson** [comment]
Perfect. Thanks!

**Pull request merged**
